-- -----------------------------------------------------
-- Database: `ponche`
-- Generated by Codex based on the PHP sources in this repository.
-- This script rebuilds the complete schema and seeds baseline data.
-- -----------------------------------------------------

CREATE DATABASE IF NOT EXISTS `ponche`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `ponche`;

-- Disable FK checks while dropping and recreating tables
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `admin_login_logs`;
DROP TABLE IF EXISTS `administrative_hours`;
DROP TABLE IF EXISTS `attendance`;
DROP TABLE IF EXISTS `users`;

SET FOREIGN_KEY_CHECKS = 1;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `full_name` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL COMMENT 'Passwords are stored as plain text by the current application.',
  `role` VARCHAR(50) NOT NULL DEFAULT 'AGENT',
  `reset_token` VARCHAR(64) DEFAULT NULL,
  `token_expiry` DATETIME DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_unique` (`username`),
  KEY `idx_users_role` (`role`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `attendance`
-- -----------------------------------------------------
CREATE TABLE `attendance` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_attendance_user_timestamp` (`user_id`, `timestamp`),
  KEY `idx_attendance_type` (`type`),
  CONSTRAINT `fk_attendance_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `administrative_hours`
-- -----------------------------------------------------
CREATE TABLE `administrative_hours` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_admin_hours_user_timestamp` (`user_id`, `timestamp`),
  KEY `idx_admin_hours_type` (`type`),
  CONSTRAINT `fk_admin_hours_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `admin_login_logs`
-- -----------------------------------------------------
CREATE TABLE `admin_login_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `role` VARCHAR(50) NOT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `public_ip` VARCHAR(45) DEFAULT NULL,
  `location` VARCHAR(255) DEFAULT NULL,
  `login_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_admin_login_logs_user_time` (`user_id`, `login_time`),
  CONSTRAINT `fk_admin_login_logs_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Seed data
-- -----------------------------------------------------
INSERT INTO `users` (`username`, `full_name`, `password`, `role`)
VALUES
  ('admin', 'System Administrator', 'admin123', 'Admin'),
  ('itmanager', 'IT Manager', 'password123', 'IT'),
  ('agentdemo', 'Demo Agent', 'defaultpassword', 'AGENT');

