<?php
/**
 * Daily Payroll Month-to-Date Report
 *
 * Replicates the calculation of admin_daily_excel.php (the "Exportar diario"
 * button in hr_report.php) and produces:
 *   - An Excel (.xls, HTML-table format) file identical to the manual export,
 *     written to a temp path so it can be attached to an email.
 *   - Structured report data (per-row + totals + by-department + by-user).
 *   - HTML email body with top-level totals and summary tables.
 *   - Optional narrative executive summary generated by Claude AI.
 *
 * Scope: only administrative users (role <> 'AGENT'), month-to-date by default
 * (configurable).
 */

require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/claude_api_client.php';

if (!function_exists('getPayrollReportSettings')) {
    function getPayrollReportSettings(PDO $pdo): array
    {
        $defaults = [
            'payroll_report_enabled'            => '0',
            'payroll_report_time'               => '08:00',
            'payroll_report_recipients'         => '',
            'payroll_report_period_mode'        => 'month_to_yesterday',
            'payroll_report_claude_enabled'     => '0',
            'payroll_report_claude_model'       => 'claude-sonnet-4-6',
            'payroll_report_claude_max_tokens'  => '1000',
            'payroll_report_claude_prompt'      => '',
        ];
        try {
            $stmt = $pdo->query("SELECT setting_key, setting_value FROM system_settings WHERE setting_key LIKE 'payroll_report_%'");
            foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) ?: [] as $row) {
                $defaults[$row['setting_key']] = $row['setting_value'] ?? '';
            }
        } catch (PDOException $e) {
            error_log('getPayrollReportSettings: ' . $e->getMessage());
        }
        return $defaults;
    }
}

if (!function_exists('getPayrollReportRecipients')) {
    function getPayrollReportRecipients(PDO $pdo): array
    {
        $raw = (string) (getPayrollReportSettings($pdo)['payroll_report_recipients'] ?? '');
        if ($raw === '') return [];
        $emails = array_map('trim', preg_split('/[,;\s]+/', $raw) ?: []);
        return array_values(array_filter($emails, static fn($e) => $e !== '' && filter_var($e, FILTER_VALIDATE_EMAIL)));
    }
}

if (!function_exists('computePayrollAmountFromSeconds')) {
    /**
     * Same cent-precision algorithm as admin_daily_excel.php::calculateAmountFromSeconds().
     */
    function computePayrollAmountFromSeconds(int $seconds, float $rate): float
    {
        if ($seconds <= 0 || $rate <= 0) return 0.0;
        $rateCents = (int) round($rate * 100);
        if ($rateCents <= 0) return 0.0;
        $amountCents = (int) round(($seconds * $rateCents) / 3600);
        return $amountCents / 100;
    }
}

if (!function_exists('resolvePayrollPeriod')) {
    /**
     * Returns [startDate, endDate] based on configured period mode.
     */
    function resolvePayrollPeriod(string $periodMode, ?string $overrideStart = null, ?string $overrideEnd = null): array
    {
        if ($overrideStart && $overrideEnd && preg_match('/^\d{4}-\d{2}-\d{2}$/', $overrideStart) && preg_match('/^\d{4}-\d{2}-\d{2}$/', $overrideEnd)) {
            return [$overrideStart, $overrideEnd];
        }
        switch ($periodMode) {
            case 'last_7_days':
                return [date('Y-m-d', strtotime('-6 days')), date('Y-m-d')];
            case 'month_to_yesterday':
            default:
                $start = date('Y-m-01');
                $end   = date('Y-m-d', strtotime('yesterday'));
                if ($end < $start) $end = $start;
                return [$start, $end];
        }
    }
}

if (!function_exists('generateDailyPayrollReport')) {
    /**
     * Builds the full structured report for the given date range.
     *
     * @return array Report data with rows, totals, by_department, by_user.
     */
    function generateDailyPayrollReport(PDO $pdo, string $startDate, string $endDate): array
    {
        $startBound = $startDate . ' 00:00:00';
        $endBound   = $endDate   . ' 23:59:59';

        $paidTypes = getPaidAttendanceTypeSlugs($pdo);
        $paidTypesUpper = array_map('strtoupper', $paidTypes ?: []);
        $compensation   = getUserCompensation($pdo);

        // Only administrative users (matches admin_daily_excel.php)
        $users = $pdo->query("SELECT id, full_name, username, department_id, role FROM users WHERE UPPER(role) <> 'AGENT' ORDER BY full_name")
                     ->fetchAll(PDO::FETCH_ASSOC) ?: [];

        $rows       = [];
        $byUser     = [];
        $byDepartment = [];
        $totals     = [
            'rows'            => 0,
            'seconds'         => 0,
            'hours'           => 0.0,
            'pay_usd'         => 0.0,
            'pay_dop'         => 0.0,
            'users_with_rows' => 0,
        ];

        foreach ($users as $user) {
            $userId = (int) $user['id'];
            $deptStmt = $pdo->prepare("SELECT name FROM departments WHERE id = ?");
            $deptStmt->execute([$user['department_id']]);
            $deptName = $deptStmt->fetchColumn() ?: 'Sin departamento';

            $punchesStmt = $pdo->prepare("
                SELECT timestamp, type, DATE(timestamp) as work_date
                FROM attendance
                WHERE user_id = ?
                AND timestamp BETWEEN ? AND ?
                ORDER BY timestamp ASC
            ");
            $punchesStmt->execute([$userId, $startBound, $endBound]);
            $punches = $punchesStmt->fetchAll(PDO::FETCH_ASSOC) ?: [];

            $punchesByDate = [];
            foreach ($punches as $p) {
                $punchesByDate[$p['work_date']][] = $p;
            }

            $comp = $compensation[$user['username']] ?? ['hourly_rate' => 0.0, 'hourly_rate_dop' => 0.0];

            $userSeconds = 0;
            $userPayUsd  = 0.0;
            $userPayDop  = 0.0;
            $userRows    = 0;

            foreach ($punchesByDate as $date => $dayPunches) {
                $inPaid = false;
                $paidStart = null;
                $lastPaid  = null;
                $firstEntry = null;
                $lastExit   = null;
                $productiveSeconds = 0;

                foreach ($dayPunches as $punch) {
                    $ts        = strtotime($punch['timestamp']);
                    $typeUpper = strtoupper($punch['type']);

                    if ($typeUpper === 'ENTRY' && $firstEntry === null) $firstEntry = $punch['timestamp'];
                    if ($typeUpper === 'EXIT') $lastExit = $punch['timestamp'];

                    $isPaid = in_array($typeUpper, $paidTypesUpper, true);
                    if ($isPaid) {
                        $lastPaid = $ts;
                        if (!$inPaid) { $paidStart = $ts; $inPaid = true; }
                    } elseif ($inPaid) {
                        if ($paidStart !== null && $lastPaid !== null) {
                            $productiveSeconds += ($lastPaid - $paidStart);
                        }
                        $inPaid = false; $paidStart = null; $lastPaid = null;
                    }
                }
                if ($inPaid && $paidStart !== null && $lastPaid !== null) {
                    $productiveSeconds += ($lastPaid - $paidStart);
                }
                if ($productiveSeconds <= 0) continue;

                $payUsd = computePayrollAmountFromSeconds($productiveSeconds, (float) $comp['hourly_rate']);
                $payDop = computePayrollAmountFromSeconds($productiveSeconds, (float) $comp['hourly_rate_dop']);

                $rows[] = [
                    'date'        => $date,
                    'user_id'     => $userId,
                    'username'    => $user['username'],
                    'full_name'   => $user['full_name'],
                    'department'  => $deptName,
                    'first_entry' => $firstEntry,
                    'last_exit'   => $lastExit,
                    'seconds'     => $productiveSeconds,
                    'hours'       => $productiveSeconds / 3600,
                    'pay_usd'     => $payUsd,
                    'pay_dop'     => $payDop,
                ];

                $userSeconds += $productiveSeconds;
                $userPayUsd  += $payUsd;
                $userPayDop  += $payDop;
                $userRows++;

                $totals['rows']++;
                $totals['seconds'] += $productiveSeconds;
                $totals['pay_usd'] += $payUsd;
                $totals['pay_dop'] += $payDop;
            }

            if ($userRows > 0) {
                $totals['users_with_rows']++;
                $byUser[] = [
                    'user_id'    => $userId,
                    'username'   => $user['username'],
                    'full_name'  => $user['full_name'],
                    'department' => $deptName,
                    'rows'       => $userRows,
                    'seconds'    => $userSeconds,
                    'hours'      => $userSeconds / 3600,
                    'pay_usd'    => $userPayUsd,
                    'pay_dop'    => $userPayDop,
                ];

                if (!isset($byDepartment[$deptName])) {
                    $byDepartment[$deptName] = [
                        'name' => $deptName, 'users' => 0, 'rows' => 0,
                        'seconds' => 0, 'hours' => 0.0, 'pay_usd' => 0.0, 'pay_dop' => 0.0,
                    ];
                }
                $byDepartment[$deptName]['users']++;
                $byDepartment[$deptName]['rows']    += $userRows;
                $byDepartment[$deptName]['seconds'] += $userSeconds;
                $byDepartment[$deptName]['hours']   += $userSeconds / 3600;
                $byDepartment[$deptName]['pay_usd'] += $userPayUsd;
                $byDepartment[$deptName]['pay_dop'] += $userPayDop;
            }
        }

        $totals['hours'] = $totals['seconds'] / 3600;

        // Sort: top payees first
        usort($byUser, static fn($a, $b) => $b['pay_usd'] <=> $a['pay_usd']);

        // Sort departments by pay_usd DESC
        uasort($byDepartment, static fn($a, $b) => $b['pay_usd'] <=> $a['pay_usd']);

        // Month progression (how far along in the month are we)
        $startTs = strtotime($startDate);
        $endTs   = strtotime($endDate);
        $daysElapsed = max(1, (int) round(($endTs - $startTs) / 86400) + 1);
        $daysInMonth = (int) date('t', $endTs);
        $daysRemaining = max(0, $daysInMonth - (int) date('j', $endTs));

        // Projection (simple linear)
        $projection = [
            'avg_daily_usd'    => $daysElapsed > 0 ? $totals['pay_usd'] / $daysElapsed : 0.0,
            'avg_daily_dop'    => $daysElapsed > 0 ? $totals['pay_dop'] / $daysElapsed : 0.0,
            'projected_usd'    => $daysElapsed > 0 ? ($totals['pay_usd'] / $daysElapsed) * $daysInMonth : 0.0,
            'projected_dop'    => $daysElapsed > 0 ? ($totals['pay_dop'] / $daysElapsed) * $daysInMonth : 0.0,
            'days_elapsed'     => $daysElapsed,
            'days_in_month'    => $daysInMonth,
            'days_remaining'   => $daysRemaining,
        ];

        return [
            'start_date'      => $startDate,
            'end_date'        => $endDate,
            'period_label'    => payrollPeriodLabel($startDate, $endDate),
            'rows'            => $rows,
            'by_user'         => $byUser,
            'by_department'   => array_values($byDepartment),
            'totals'          => $totals,
            'projection'      => $projection,
            'generated_at'    => date('Y-m-d H:i:s'),
        ];
    }
}

if (!function_exists('payrollPeriodLabel')) {
    function payrollPeriodLabel(string $start, string $end): string
    {
        $months = ['01' => 'enero', '02' => 'febrero', '03' => 'marzo', '04' => 'abril',
                   '05' => 'mayo', '06' => 'junio', '07' => 'julio', '08' => 'agosto',
                   '09' => 'septiembre', '10' => 'octubre', '11' => 'noviembre', '12' => 'diciembre'];
        $sTs = strtotime($start);
        $eTs = strtotime($end);
        $sMonth = $months[date('m', $sTs)] ?? date('m', $sTs);
        $eMonth = $months[date('m', $eTs)] ?? date('m', $eTs);
        if (date('Y-m', $sTs) === date('Y-m', $eTs)) {
            return sprintf('%d al %d de %s de %s',
                (int) date('j', $sTs), (int) date('j', $eTs), $sMonth, date('Y', $sTs));
        }
        return sprintf('%d de %s de %s — %d de %s de %s',
            (int) date('j', $sTs), $sMonth, date('Y', $sTs),
            (int) date('j', $eTs), $eMonth, date('Y', $eTs));
    }
}

if (!function_exists('writePayrollExcelFile')) {
    /**
     * Writes a proper .xlsx file (PhpSpreadsheet) to a temp path and returns the absolute path.
     * Produces a styled workbook with:
     *   - Sheet 1: Detalle (row-per-day-per-user)
     *   - Sheet 2: Totales por colaborador
     *   - Sheet 3: Totales por departamento
     */
    function writePayrollExcelFile(array $reportData, ?string $outputPath = null): string
    {
        require_once __DIR__ . '/../vendor/autoload.php';

        if ($outputPath === null) {
            $tmpDir = sys_get_temp_dir();
            $fileName = sprintf('admin_diario_%s_al_%s.xlsx', $reportData['start_date'], $reportData['end_date']);
            $outputPath = rtrim($tmpDir, "/\\") . DIRECTORY_SEPARATOR . $fileName;
        }

        $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

        // ---------- Sheet 1: Detalle ----------
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Detalle');

        $headers = ['Fecha', 'Colaborador', 'Departamento', 'Entrada', 'Salida', 'Horas', 'Pago USD', 'Pago DOP'];
        $sheet->fromArray($headers, null, 'A1');

        // Header styling
        $headerStyle = [
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID, 'startColor' => ['rgb' => '047857']],
            'alignment' => ['horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER, 'vertical' => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER],
            'borders' => ['allBorders' => ['borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN, 'color' => ['rgb' => '065F46']]],
        ];
        $sheet->getStyle('A1:H1')->applyFromArray($headerStyle);
        $sheet->getRowDimension(1)->setRowHeight(24);

        $rowNum = 2;
        if (!empty($reportData['rows'])) {
            foreach ($reportData['rows'] as $row) {
                $entry = $row['first_entry'] ? date('H:i', strtotime($row['first_entry'])) : 'Sin registro';
                $exit  = $row['last_exit']   ? date('H:i', strtotime($row['last_exit']))   : 'Sin registro';

                $sheet->setCellValue('A' . $rowNum, date('d/m/Y', strtotime($row['date'])));
                $sheet->setCellValue('B' . $rowNum, $row['full_name']);
                $sheet->setCellValue('C' . $rowNum, $row['department']);
                $sheet->setCellValue('D' . $rowNum, $entry);
                $sheet->setCellValue('E' . $rowNum, $exit);
                $sheet->setCellValue('F' . $rowNum, round((float) $row['hours'], 2));
                $sheet->setCellValue('G' . $rowNum, round((float) $row['pay_usd'], 2));
                $sheet->setCellValue('H' . $rowNum, round((float) $row['pay_dop'], 2));
                $rowNum++;
            }

            // Totals row
            $sheet->setCellValue('A' . $rowNum, 'TOTAL');
            $sheet->setCellValue('F' . $rowNum, '=SUM(F2:F' . ($rowNum - 1) . ')');
            $sheet->setCellValue('G' . $rowNum, '=SUM(G2:G' . ($rowNum - 1) . ')');
            $sheet->setCellValue('H' . $rowNum, '=SUM(H2:H' . ($rowNum - 1) . ')');
            $sheet->getStyle('A' . $rowNum . ':H' . $rowNum)->applyFromArray([
                'font' => ['bold' => true],
                'fill' => ['fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID, 'startColor' => ['rgb' => 'D1FAE5']],
                'borders' => ['top' => ['borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_DOUBLE]],
            ]);
            $dataEnd = $rowNum;
        } else {
            $sheet->setCellValue('A2', 'Sin registros administrativos en el rango solicitado.');
            $sheet->mergeCells('A2:H2');
            $sheet->getStyle('A2')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
            $dataEnd = 2;
        }

        // Format hours/money columns
        if ($dataEnd >= 2) {
            $sheet->getStyle('F2:F' . $dataEnd)->getNumberFormat()->setFormatCode('0.00');
            $sheet->getStyle('G2:G' . $dataEnd)->getNumberFormat()->setFormatCode('"$"#,##0.00');
            $sheet->getStyle('H2:H' . $dataEnd)->getNumberFormat()->setFormatCode('"RD$"#,##0.00');
        }

        foreach (['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'] as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
        }
        $sheet->freezePane('A2');

        // ---------- Sheet 2: Por colaborador ----------
        $sheetUser = $spreadsheet->createSheet();
        $sheetUser->setTitle('Por colaborador');
        $sheetUser->fromArray(['Colaborador', 'Usuario', 'Departamento', 'Días', 'Horas', 'Pago USD', 'Pago DOP'], null, 'A1');
        $sheetUser->getStyle('A1:G1')->applyFromArray($headerStyle);

        $r = 2;
        foreach ($reportData['by_user'] ?? [] as $u) {
            $sheetUser->setCellValue('A' . $r, $u['full_name']);
            $sheetUser->setCellValue('B' . $r, $u['username']);
            $sheetUser->setCellValue('C' . $r, $u['department']);
            $sheetUser->setCellValue('D' . $r, $u['rows']);
            $sheetUser->setCellValue('E' . $r, round((float) $u['hours'], 2));
            $sheetUser->setCellValue('F' . $r, round((float) $u['pay_usd'], 2));
            $sheetUser->setCellValue('G' . $r, round((float) $u['pay_dop'], 2));
            $r++;
        }
        if ($r > 2) {
            $sheetUser->getStyle('E2:E' . ($r - 1))->getNumberFormat()->setFormatCode('0.00');
            $sheetUser->getStyle('F2:F' . ($r - 1))->getNumberFormat()->setFormatCode('"$"#,##0.00');
            $sheetUser->getStyle('G2:G' . ($r - 1))->getNumberFormat()->setFormatCode('"RD$"#,##0.00');
        }
        foreach (['A', 'B', 'C', 'D', 'E', 'F', 'G'] as $col) {
            $sheetUser->getColumnDimension($col)->setAutoSize(true);
        }
        $sheetUser->freezePane('A2');

        // ---------- Sheet 3: Por departamento ----------
        $sheetDept = $spreadsheet->createSheet();
        $sheetDept->setTitle('Por departamento');
        $sheetDept->fromArray(['Departamento', 'Colaboradores', 'Horas', 'Pago USD', 'Pago DOP'], null, 'A1');
        $sheetDept->getStyle('A1:E1')->applyFromArray($headerStyle);

        $r = 2;
        foreach ($reportData['by_department'] ?? [] as $d) {
            $sheetDept->setCellValue('A' . $r, $d['name']);
            $sheetDept->setCellValue('B' . $r, $d['users']);
            $sheetDept->setCellValue('C' . $r, round((float) $d['hours'], 2));
            $sheetDept->setCellValue('D' . $r, round((float) $d['pay_usd'], 2));
            $sheetDept->setCellValue('E' . $r, round((float) $d['pay_dop'], 2));
            $r++;
        }
        if ($r > 2) {
            $sheetDept->getStyle('C2:C' . ($r - 1))->getNumberFormat()->setFormatCode('0.00');
            $sheetDept->getStyle('D2:D' . ($r - 1))->getNumberFormat()->setFormatCode('"$"#,##0.00');
            $sheetDept->getStyle('E2:E' . ($r - 1))->getNumberFormat()->setFormatCode('"RD$"#,##0.00');
        }
        foreach (['A', 'B', 'C', 'D', 'E'] as $col) {
            $sheetDept->getColumnDimension($col)->setAutoSize(true);
        }
        $sheetDept->freezePane('A2');

        // Reset active sheet to the first one
        $spreadsheet->setActiveSheetIndex(0);

        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
        $writer->save($outputPath);

        return $outputPath;
    }
}

if (!function_exists('generateAIPayrollSummary')) {
    function generateAIPayrollSummary(PDO $pdo, array $reportData): string
    {
        $settings = getPayrollReportSettings($pdo);
        if (($settings['payroll_report_claude_enabled'] ?? '0') !== '1') {
            return '';
        }
        if (empty($reportData['by_user'])) {
            return '';
        }

        $model = trim((string) ($settings['payroll_report_claude_model'] ?? '')) ?: resolveAnthropicDefaultModel($pdo);
        $maxTokens = max(100, (int) ($settings['payroll_report_claude_max_tokens'] ?? 1000));
        $systemPrompt = (string) ($settings['payroll_report_claude_prompt'] ?? '');

        $payload = [
            'periodo'        => $reportData['period_label'],
            'inicio'         => $reportData['start_date'],
            'fin'            => $reportData['end_date'],
            'totales'        => $reportData['totals'],
            'proyeccion'     => $reportData['projection'],
            'por_departamento' => $reportData['by_department'],
            'por_colaborador' => array_map(static function ($u) {
                return [
                    'nombre'     => $u['full_name'],
                    'departamento' => $u['department'],
                    'horas'      => round($u['hours'], 2),
                    'pago_usd'   => round($u['pay_usd'], 2),
                    'pago_dop'   => round($u['pay_dop'], 2),
                    'dias_con_actividad' => $u['rows'],
                ];
            }, $reportData['by_user']),
        ];

        $userPrompt = "Aquí está el corte acumulado de nómina del mes en curso. Genera el resumen ejecutivo según las instrucciones:\n\n"
            . json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);

        $result = callClaudeAPI([
            'api_key'       => '',
            'model'         => $model,
            'system_prompt' => $systemPrompt,
            'user_prompt'   => $userPrompt,
            'max_tokens'    => $maxTokens,
            'temperature'   => 0.2,
            'pdo'           => $pdo,
        ]);

        if (!$result['success']) {
            error_log('[payroll_report] Claude API error: ' . ($result['error'] ?? 'unknown'));
            return '';
        }
        return (string) $result['content'];
    }
}

if (!function_exists('generatePayrollReportHTML')) {
    function generatePayrollReportHTML(array $reportData, string $aiSummary = ''): string
    {
        $period     = htmlspecialchars($reportData['period_label']);
        $totals     = $reportData['totals'];
        $byUser     = $reportData['by_user'];
        $byDept     = $reportData['by_department'];
        $projection = $reportData['projection'];

        $aiBlock = '';
        if (trim($aiSummary) !== '') {
            $safe = nl2br(htmlspecialchars($aiSummary), false);
            $aiBlock = "<div class='ai-summary'>"
                . "<div class='ai-badge'>Resumen ejecutivo generado por IA</div>"
                . "<div class='ai-body'>{$safe}</div>"
                . "</div>";
        }

        // Department table
        $deptRows = '';
        foreach ($byDept as $d) {
            $share = $totals['pay_usd'] > 0 ? ($d['pay_usd'] / $totals['pay_usd']) * 100 : 0;
            $deptRows .= "<tr>"
                . "<td><strong>" . htmlspecialchars($d['name']) . "</strong></td>"
                . "<td class='num'>{$d['users']}</td>"
                . "<td class='num'>" . number_format($d['hours'], 2) . "</td>"
                . "<td class='num'>$" . number_format($d['pay_usd'], 2) . "</td>"
                . "<td class='num'>RD$" . number_format($d['pay_dop'], 2) . "</td>"
                . "<td class='num'>" . number_format($share, 1) . "%</td>"
                . "</tr>";
        }
        if (empty($deptRows)) {
            $deptRows = "<tr><td colspan='6' class='no-data'>Sin datos en el rango.</td></tr>";
        }

        // Top 10 users table
        $userRows = '';
        foreach (array_slice($byUser, 0, 15) as $u) {
            $userRows .= "<tr>"
                . "<td><strong>" . htmlspecialchars($u['full_name']) . "</strong><br><span class='muted'>" . htmlspecialchars($u['username']) . "</span></td>"
                . "<td>" . htmlspecialchars($u['department']) . "</td>"
                . "<td class='num'>{$u['rows']}</td>"
                . "<td class='num'>" . number_format($u['hours'], 2) . "</td>"
                . "<td class='num'>$" . number_format($u['pay_usd'], 2) . "</td>"
                . "<td class='num'>RD$" . number_format($u['pay_dop'], 2) . "</td>"
                . "</tr>";
        }
        if (empty($userRows)) {
            $userRows = "<tr><td colspan='6' class='no-data'>Sin colaboradores con actividad.</td></tr>";
        }

        $totUsd  = number_format($totals['pay_usd'], 2);
        $totDop  = number_format($totals['pay_dop'], 2);
        $totHrs  = number_format($totals['hours'], 2);
        $projUsd = number_format($projection['projected_usd'], 2);
        $projDop = number_format($projection['projected_dop'], 2);

        return <<<HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; color: #333; margin: 0; padding: 0; background-color: #f5f5f5; line-height: 1.5; }
  .container { max-width: 1100px; margin: 0 auto; padding: 20px; }
  .header { background: linear-gradient(135deg, #10b981 0%, #047857 100%); color: #fff; padding: 28px; text-align: center; border-radius: 10px; }
  .header h1 { margin: 0; font-size: 26px; font-weight: 600; }
  .header p { margin: 8px 0 0 0; font-size: 15px; opacity: 0.95; }
  .stats-grid { display: table; width: 100%; margin: 18px 0; border-spacing: 10px; }
  .stat-card { display: table-cell; background: #fff; padding: 18px; border-radius: 8px; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,0.08); }
  .stat-card.primary  { border-top: 4px solid #0ea5e9; }
  .stat-card.success  { border-top: 4px solid #10b981; }
  .stat-card.warning  { border-top: 4px solid #f59e0b; }
  .stat-card.muted    { border-top: 4px solid #64748b; }
  .stat-number { font-size: 24px; font-weight: 700; margin: 8px 0 0 0; }
  .stat-label  { color: #666; font-size: 12px; text-transform: uppercase; letter-spacing: .5px; }
  .ai-summary { background: #fffbeb; border: 1px solid #fcd34d; border-left: 4px solid #f59e0b; padding: 16px 20px; border-radius: 8px; margin: 18px 0; }
  .ai-badge { display: inline-block; background: #f59e0b; color: #fff; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 600; text-transform: uppercase; margin-bottom: 10px; }
  .ai-body { color: #333; font-size: 14px; white-space: pre-wrap; }
  .section { background: #fff; margin: 18px 0; padding: 22px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.08); }
  .section h2 { margin: 0 0 14px 0; font-size: 18px; border-bottom: 2px solid #10b981; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  thead { background: linear-gradient(135deg, #10b981 0%, #047857 100%); }
  th { color: #fff; padding: 10px 8px; text-align: left; font-weight: 600; font-size: 12px; }
  td { padding: 10px 8px; border-bottom: 1px solid #eee; vertical-align: top; }
  tbody tr:nth-child(even) { background-color: #fafafa; }
  td.num { font-family: 'Courier New', monospace; white-space: nowrap; text-align: right; }
  .muted { color: #888; font-size: 11px; }
  .attachment-note { background: #eff6ff; border: 1px solid #bfdbfe; color: #1e40af; padding: 12px 16px; border-radius: 8px; font-size: 14px; margin: 14px 0; }
  .no-data { text-align: center; padding: 20px; color: #666; font-style: italic; }
  .footer { text-align: center; padding: 18px; color: #777; font-size: 12px; margin-top: 20px; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Corte de Nómina Acumulado</h1>
    <p>{$period}</p>
  </div>

  <div class="stats-grid">
    <div class="stat-card success">
      <div class="stat-label">Pago acumulado USD</div>
      <div class="stat-number">\${$totUsd}</div>
    </div>
    <div class="stat-card success">
      <div class="stat-label">Pago acumulado DOP</div>
      <div class="stat-number">RD\${$totDop}</div>
    </div>
    <div class="stat-card primary">
      <div class="stat-label">Horas productivas</div>
      <div class="stat-number">{$totHrs}</div>
    </div>
    <div class="stat-card muted">
      <div class="stat-label">Colaboradores con actividad</div>
      <div class="stat-number">{$totals['users_with_rows']}</div>
    </div>
  </div>

  <div class="stats-grid">
    <div class="stat-card warning">
      <div class="stat-label">Proyección cierre USD</div>
      <div class="stat-number">\${$projUsd}</div>
    </div>
    <div class="stat-card warning">
      <div class="stat-label">Proyección cierre DOP</div>
      <div class="stat-number">RD\${$projDop}</div>
    </div>
    <div class="stat-card muted">
      <div class="stat-label">Días transcurridos</div>
      <div class="stat-number">{$projection['days_elapsed']} / {$projection['days_in_month']}</div>
    </div>
  </div>

  {$aiBlock}

  <div class="attachment-note">
    <i class="fas fa-paperclip"></i> <strong>Excel adjunto:</strong> detalle completo día por día y colaborador (mismo formato que el botón "Exportar diario" del módulo de RH).
  </div>

  <div class="section">
    <h2>Resumen por departamento</h2>
    <table>
      <thead>
        <tr>
          <th>Departamento</th>
          <th style="text-align:right;">Colabs.</th>
          <th style="text-align:right;">Horas</th>
          <th style="text-align:right;">Pago USD</th>
          <th style="text-align:right;">Pago DOP</th>
          <th style="text-align:right;">% del total</th>
        </tr>
      </thead>
      <tbody>{$deptRows}</tbody>
    </table>
  </div>

  <div class="section">
    <h2>Top 15 colaboradores (por pago acumulado USD)</h2>
    <table>
      <thead>
        <tr>
          <th>Colaborador</th>
          <th>Departamento</th>
          <th style="text-align:right;">Días</th>
          <th style="text-align:right;">Horas</th>
          <th style="text-align:right;">Pago USD</th>
          <th style="text-align:right;">Pago DOP</th>
        </tr>
      </thead>
      <tbody>{$userRows}</tbody>
    </table>
  </div>

  <div class="footer">
    <p><strong>Reporte generado automáticamente</strong></p>
    <p>{$reportData['generated_at']} — Sistema de Control de Asistencia</p>
  </div>
</div>
</body>
</html>
HTML;
    }
}

if (!function_exists('sendPayrollReportByEmail')) {
    /**
     * Generates the Excel, writes it to temp, sends email with it as attachment,
     * then cleans up the file.
     */
    function sendPayrollReportByEmail(PDO $pdo, array $reportData, array $recipients, string $aiSummary = ''): bool
    {
        if (empty($recipients)) {
            error_log('[payroll_report] No recipients configured');
            return false;
        }

        $html = generatePayrollReportHTML($reportData, $aiSummary);

        // Write Excel to temp path
        $excelPath = null;
        try {
            $excelPath = writePayrollExcelFile($reportData);
        } catch (Throwable $e) {
            error_log('[payroll_report] Could not create Excel: ' . $e->getMessage());
            // Continue without attachment — body still has a full summary
        }

        require_once __DIR__ . '/email_functions.php';
        $result = sendDailyPayrollReport($html, $recipients, $reportData, $excelPath);

        // Clean up temp file
        if ($excelPath && file_exists($excelPath)) {
            @unlink($excelPath);
        }

        if ($result['success']) {
            error_log('[payroll_report] Sent: ' . $result['message']);
            return true;
        }
        error_log('[payroll_report] Failed: ' . $result['message']);
        return false;
    }
}
