<?php
/**
 * Daily Quality Alerts Report
 *
 * Fetches evaluations from the `hhempeos_calidad` database for the target day
 * (default: yesterday) with percentage below the configured threshold, groups
 * them by agent, and produces a structured array + HTML email body.
 *
 * Optionally adds a narrative executive summary generated by Claude with
 * pattern detection across the alerts.
 */

require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../quality_db.php';
require_once __DIR__ . '/claude_api_client.php';

if (!function_exists('getQualityAlertsReportSettings')) {
    /**
     * Returns all quality_alerts_report_* settings merged with defaults.
     */
    function getQualityAlertsReportSettings(PDO $pdo): array
    {
        $defaults = [
            'quality_alerts_report_enabled'            => '0',
            'quality_alerts_report_time'               => '07:30',
            'quality_alerts_report_recipients'         => '',
            'quality_alerts_report_threshold'          => '80',
            'quality_alerts_report_only_with_evals'    => '1',
            'quality_alerts_report_claude_enabled'     => '0',
            'quality_alerts_report_claude_api_key'     => '',
            'quality_alerts_report_claude_model'       => 'claude-sonnet-4-6',
            'quality_alerts_report_claude_max_tokens'  => '900',
            'quality_alerts_report_claude_prompt'      => '',
        ];

        try {
            $stmt = $pdo->query("
                SELECT setting_key, setting_value
                FROM system_settings
                WHERE setting_key LIKE 'quality_alerts_report_%'
            ");
            foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) ?: [] as $row) {
                $defaults[$row['setting_key']] = $row['setting_value'] ?? '';
            }
        } catch (PDOException $e) {
            error_log('getQualityAlertsReportSettings: ' . $e->getMessage());
        }

        return $defaults;
    }
}

if (!function_exists('getQualityAlertsReportRecipients')) {
    function getQualityAlertsReportRecipients(PDO $pdo): array
    {
        $settings = getQualityAlertsReportSettings($pdo);
        $raw = (string) ($settings['quality_alerts_report_recipients'] ?? '');
        if ($raw === '') {
            return [];
        }
        $emails = array_map('trim', preg_split('/[,;\s]+/', $raw) ?: []);
        return array_values(array_filter($emails, static function ($email) {
            return $email !== '' && filter_var($email, FILTER_VALIDATE_EMAIL);
        }));
    }
}

if (!function_exists('strftimeSpanish')) {
    function strftimeSpanish(string $date): string
    {
        $days = ['Sunday' => 'Domingo', 'Monday' => 'Lunes', 'Tuesday' => 'Martes',
                 'Wednesday' => 'Miércoles', 'Thursday' => 'Jueves', 'Friday' => 'Viernes',
                 'Saturday' => 'Sábado'];
        $months = ['January' => 'enero', 'February' => 'febrero', 'March' => 'marzo',
                   'April' => 'abril', 'May' => 'mayo', 'June' => 'junio', 'July' => 'julio',
                   'August' => 'agosto', 'September' => 'septiembre', 'October' => 'octubre',
                   'November' => 'noviembre', 'December' => 'diciembre'];
        $ts = strtotime($date);
        if ($ts === false) return $date;
        return sprintf('%s, %d de %s de %s',
            $days[date('l', $ts)] ?? date('l', $ts),
            (int) date('j', $ts),
            $months[date('F', $ts)] ?? date('F', $ts),
            date('Y', $ts));
    }
}

if (!function_exists('generateDailyQualityAlertsReport')) {
    /**
     * Builds the report data.
     *
     * @param PDO $pdo Main DB (for settings + logging).
     * @param string|null $date YYYY-MM-DD, defaults to yesterday.
     * @return array{available: bool, ...}
     */
    function generateDailyQualityAlertsReport(PDO $pdo, ?string $date = null): array
    {
        $date = $date ?: date('Y-m-d', strtotime('yesterday'));
        $settings = getQualityAlertsReportSettings($pdo);
        $threshold = (float) ($settings['quality_alerts_report_threshold'] ?? 80);

        $qualityPdo = getQualityDbConnection();

        if (!$qualityPdo instanceof PDO) {
            return [
                'available'      => false,
                'error'          => 'No se pudo conectar a la base de calidad.',
                'date'           => $date,
                'date_formatted' => strftimeSpanish($date),
                'threshold'      => $threshold,
                'alerts'         => [],
                'by_agent'       => [],
                'by_campaign'    => [],
                'totals'         => [
                    'total_alerts'    => 0,
                    'agents_affected' => 0,
                    'campaigns_affected' => 0,
                    'avg_score'       => 0.0,
                    'lowest_score'    => null,
                ],
                'generated_at'   => date('Y-m-d H:i:s'),
            ];
        }

        try {
            $stmt = $qualityPdo->prepare("
                SELECT
                    e.id                 AS evaluation_id,
                    e.agent_id,
                    e.campaign_id,
                    e.call_id,
                    e.percentage,
                    e.total_score,
                    e.max_possible_score,
                    e.general_comments,
                    e.improvement_areas,
                    e.improvement_plan,
                    e.tasks_commitments,
                    e.call_date,
                    e.created_at,
                    u.username           AS agent_username,
                    u.full_name          AS agent_full_name,
                    camp.name            AS campaign_name,
                    c.call_datetime,
                    c.duration_seconds,
                    c.customer_phone,
                    c.recording_path,
                    c.call_type,
                    ai.model             AS ai_model,
                    ai.score             AS ai_score,
                    ai.summary           AS ai_summary
                FROM evaluations e
                INNER JOIN users u          ON u.id = e.agent_id
                LEFT JOIN campaigns camp    ON camp.id = e.campaign_id
                LEFT JOIN calls c           ON c.id = e.call_id
                LEFT JOIN call_ai_analytics ai ON ai.call_id = c.id
                WHERE DATE(e.created_at) = ?
                  AND e.percentage IS NOT NULL
                  AND e.percentage < ?
                ORDER BY e.percentage ASC, u.full_name ASC, e.created_at DESC
            ");
            $stmt->execute([$date, $threshold]);
            $alerts = $stmt->fetchAll(PDO::FETCH_ASSOC) ?: [];
        } catch (PDOException $e) {
            return [
                'available'      => false,
                'error'          => 'Error consultando evaluaciones: ' . $e->getMessage(),
                'date'           => $date,
                'date_formatted' => strftimeSpanish($date),
                'threshold'      => $threshold,
                'alerts'         => [],
                'by_agent'       => [],
                'by_campaign'    => [],
                'totals'         => [
                    'total_alerts'    => 0,
                    'agents_affected' => 0,
                    'campaigns_affected' => 0,
                    'avg_score'       => 0.0,
                    'lowest_score'    => null,
                ],
                'generated_at'   => date('Y-m-d H:i:s'),
            ];
        }

        // Group by agent and by campaign for summary sections
        $byAgent = [];
        $byCampaign = [];
        $sumScore = 0.0;
        $lowestScore = null;

        foreach ($alerts as $a) {
            $score = (float) $a['percentage'];
            $sumScore += $score;
            if ($lowestScore === null || $score < $lowestScore) {
                $lowestScore = $score;
            }

            $agentId = (int) $a['agent_id'];
            if (!isset($byAgent[$agentId])) {
                $byAgent[$agentId] = [
                    'agent_id'   => $agentId,
                    'username'   => $a['agent_username'],
                    'full_name'  => $a['agent_full_name'],
                    'count'      => 0,
                    'min_score'  => null,
                    'avg_score'  => 0.0,
                    'scores_sum' => 0.0,
                    'campaigns'  => [],
                    'evals'      => [],
                ];
            }
            $byAgent[$agentId]['count']++;
            $byAgent[$agentId]['scores_sum'] += $score;
            $byAgent[$agentId]['min_score'] = $byAgent[$agentId]['min_score'] === null
                ? $score
                : min($byAgent[$agentId]['min_score'], $score);
            if ($a['campaign_name']) {
                $byAgent[$agentId]['campaigns'][$a['campaign_name']] = true;
            }
            $byAgent[$agentId]['evals'][] = $a;

            $campKey = $a['campaign_name'] ?: '(Sin campaña)';
            if (!isset($byCampaign[$campKey])) {
                $byCampaign[$campKey] = ['name' => $campKey, 'count' => 0, 'agents' => []];
            }
            $byCampaign[$campKey]['count']++;
            $byCampaign[$campKey]['agents'][$agentId] = true;
        }

        foreach ($byAgent as &$ag) {
            $ag['avg_score'] = $ag['count'] > 0 ? round($ag['scores_sum'] / $ag['count'], 2) : 0.0;
            $ag['campaigns'] = array_keys($ag['campaigns']);
        }
        unset($ag);

        foreach ($byCampaign as &$c) {
            $c['agents_count'] = count($c['agents']);
            unset($c['agents']);
        }
        unset($c);

        // Sort agents by count DESC then min_score ASC
        usort($byAgent, static function ($a, $b) {
            if ($b['count'] !== $a['count']) {
                return $b['count'] <=> $a['count'];
            }
            return $a['min_score'] <=> $b['min_score'];
        });

        // Sort campaigns by count DESC
        uasort($byCampaign, static fn($a, $b) => $b['count'] <=> $a['count']);

        $totals = [
            'total_alerts'       => count($alerts),
            'agents_affected'    => count($byAgent),
            'campaigns_affected' => count($byCampaign),
            'avg_score'          => count($alerts) > 0 ? round($sumScore / count($alerts), 2) : 0.0,
            'lowest_score'       => $lowestScore,
        ];

        return [
            'available'      => true,
            'date'           => $date,
            'date_formatted' => strftimeSpanish($date),
            'threshold'      => $threshold,
            'alerts'         => $alerts,
            'by_agent'       => $byAgent,
            'by_campaign'    => $byCampaign,
            'totals'         => $totals,
            'generated_at'   => date('Y-m-d H:i:s'),
        ];
    }
}

if (!function_exists('generateAIQualityAlertsSummary')) {
    /**
     * Calls Claude for a narrative executive summary with pattern detection.
     * Returns '' on disabled / error (graceful fallback).
     */
    function generateAIQualityAlertsSummary(PDO $pdo, array $reportData): string
    {
        $settings = getQualityAlertsReportSettings($pdo);
        if (($settings['quality_alerts_report_claude_enabled'] ?? '0') !== '1') {
            return '';
        }
        if (empty($reportData['alerts'])) {
            return '';
        }

        // API key is resolved globally via resolveAnthropicApiKey().
        // Per-report 'quality_alerts_report_claude_api_key' is kept only as an optional override.
        $apiKeyOverride = trim((string) ($settings['quality_alerts_report_claude_api_key'] ?? ''));
        $model          = trim((string) ($settings['quality_alerts_report_claude_model']   ?? '')) ?: resolveAnthropicDefaultModel($pdo);
        $maxTokens      = max(100, (int) ($settings['quality_alerts_report_claude_max_tokens'] ?? 900));
        $systemPrompt   = (string) ($settings['quality_alerts_report_claude_prompt'] ?? '');

        // Compact payload
        $payload = [
            'fecha'     => $reportData['date'],
            'umbral'    => $reportData['threshold'],
            'totales'   => $reportData['totals'],
            'por_campana' => array_values($reportData['by_campaign']),
            'alertas'   => array_map(static function ($a) {
                return [
                    'agente'            => $a['agent_full_name'],
                    'username'          => $a['agent_username'],
                    'campana'           => $a['campaign_name'],
                    'score'             => (float) $a['percentage'],
                    'total'             => (int) ($a['total_score'] ?? 0),
                    'max'               => (int) ($a['max_possible_score'] ?? 0),
                    'areas_mejora'      => $a['improvement_areas'],
                    'plan_mejora'       => $a['improvement_plan'],
                    'comentarios'       => $a['general_comments'],
                    'resumen_ai'        => $a['ai_summary'],
                    'ai_score'          => $a['ai_score'] !== null ? (float) $a['ai_score'] : null,
                    'fecha_llamada'     => $a['call_datetime'] ?: $a['call_date'],
                ];
            }, $reportData['alerts']),
        ];

        $userPrompt = "Aquí está el JSON con las alertas críticas de calidad de ayer. Genera el resumen ejecutivo según las instrucciones:\n\n"
            . json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);

        $result = callClaudeAPI([
            'api_key'       => $apiKeyOverride, // '' → resolver uses global setting
            'model'         => $model,
            'system_prompt' => $systemPrompt,
            'user_prompt'   => $userPrompt,
            'max_tokens'    => $maxTokens,
            'temperature'   => 0.3,
            'pdo'           => $pdo,
        ]);

        if (!$result['success']) {
            error_log('[quality_alerts_report] Claude API error: ' . ($result['error'] ?? 'unknown'));
            return '';
        }

        return (string) $result['content'];
    }
}

if (!function_exists('generateQualityAlertsReportHTML')) {
    /**
     * Renders the HTML email body.
     */
    function generateQualityAlertsReportHTML(array $reportData, string $aiSummary = ''): string
    {
        $date     = htmlspecialchars($reportData['date_formatted']);
        $threshold = htmlspecialchars((string) $reportData['threshold']);
        $totals   = $reportData['totals'];
        $alerts   = $reportData['alerts'];
        $byAgent  = $reportData['by_agent'];
        $byCampaign = $reportData['by_campaign'];

        $connError = '';
        if (empty($reportData['available'])) {
            $connError = "<div style='background:#fef2f2;border:1px solid #fca5a5;color:#b91c1c;padding:12px 16px;border-radius:8px;margin:16px 0;'>"
                . "⚠️ " . htmlspecialchars($reportData['error'] ?? 'Error obteniendo datos de calidad.')
                . "</div>";
        }

        // AI block
        $aiBlock = '';
        if (trim($aiSummary) !== '') {
            $safe = nl2br(htmlspecialchars($aiSummary), false);
            $aiBlock = "<div class='ai-summary'>"
                . "<div class='ai-badge'>Resumen ejecutivo generado por IA</div>"
                . "<div class='ai-body'>{$safe}</div>"
                . "</div>";
        }

        // Agent summary table
        $agentRows = '';
        if (!empty($byAgent)) {
            foreach ($byAgent as $ag) {
                $campaigns = $ag['campaigns'] ? htmlspecialchars(implode(', ', $ag['campaigns'])) : '—';
                $agentRows .= "<tr>"
                    . "<td><strong>" . htmlspecialchars($ag['full_name']) . "</strong><br><span class='muted'>" . htmlspecialchars($ag['username']) . "</span></td>"
                    . "<td class='num'><strong>{$ag['count']}</strong></td>"
                    . "<td class='num'>" . number_format($ag['min_score'], 2) . "%</td>"
                    . "<td class='num'>" . number_format($ag['avg_score'], 2) . "%</td>"
                    . "<td>{$campaigns}</td>"
                    . "</tr>";
            }
        } else {
            $agentRows = "<tr><td colspan='5' class='no-data'>No hay alertas críticas para esta fecha.</td></tr>";
        }

        // Campaign summary table
        $campaignRows = '';
        if (!empty($byCampaign)) {
            foreach ($byCampaign as $c) {
                $campaignRows .= "<tr>"
                    . "<td>" . htmlspecialchars($c['name']) . "</td>"
                    . "<td class='num'><strong>{$c['count']}</strong></td>"
                    . "<td class='num'>{$c['agents_count']}</td>"
                    . "</tr>";
            }
        }

        // Detail list (each evaluation)
        $detailBlocks = '';
        foreach ($alerts as $a) {
            $agent    = htmlspecialchars($a['agent_full_name']);
            $campaign = htmlspecialchars($a['campaign_name'] ?: '(Sin campaña)');
            $score    = number_format((float) $a['percentage'], 2);
            $when     = htmlspecialchars(date('d/m/Y H:i', strtotime($a['call_datetime'] ?: $a['created_at'])));
            $phone    = htmlspecialchars($a['customer_phone'] ?? '');
            $areas    = nl2br(htmlspecialchars((string) ($a['improvement_areas'] ?? '')), false);
            $plan     = nl2br(htmlspecialchars((string) ($a['improvement_plan'] ?? '')), false);
            $comments = nl2br(htmlspecialchars((string) ($a['general_comments'] ?? '')), false);
            $aiSum    = nl2br(htmlspecialchars((string) ($a['ai_summary'] ?? '')), false);
            $aiScore  = $a['ai_score'] !== null ? number_format((float) $a['ai_score'], 2) : '—';

            $improvBlock = '';
            if (trim((string) $a['improvement_areas']) !== '') {
                $improvBlock .= "<div class='improv-box'><strong>Áreas de mejora:</strong><br>{$areas}</div>";
            }
            if (trim((string) $a['improvement_plan']) !== '') {
                $improvBlock .= "<div class='improv-box'><strong>Plan de mejora:</strong><br>{$plan}</div>";
            }
            if (trim((string) $a['general_comments']) !== '') {
                $improvBlock .= "<div class='improv-box'><strong>Comentarios:</strong><br>{$comments}</div>";
            }
            if (trim((string) $a['ai_summary']) !== '') {
                $improvBlock .= "<div class='improv-box ai-box'><strong>Resumen AI (score {$aiScore}):</strong><br>{$aiSum}</div>";
            }

            $detailBlocks .= "<div class='alert-card'>"
                . "<div class='alert-head'>"
                .   "<div><strong class='alert-agent'>{$agent}</strong>"
                .     "<span class='chip'>{$campaign}</span>"
                .   "</div>"
                .   "<div class='alert-score'>{$score}%</div>"
                . "</div>"
                . "<div class='alert-meta'>"
                .   "<span>📞 {$when}</span>"
                .   ($phone ? "<span>Cliente: {$phone}</span>" : "")
                .   "<span>Call ID: " . htmlspecialchars((string) $a['call_id']) . "</span>"
                . "</div>"
                . $improvBlock
                . "</div>";
        }

        if (empty($alerts) && empty($connError)) {
            $detailBlocks = "<div class='no-data-success'><h3>✅ ¡Excelente!</h3><p>No hay alertas críticas de calidad para este día. Todas las evaluaciones estuvieron en o por encima del umbral de {$threshold}%.</p></div>";
        }

        $lowest = $totals['lowest_score'] !== null ? number_format((float) $totals['lowest_score'], 2) . '%' : '—';

        return <<<HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; color: #333; margin: 0; padding: 0; background-color: #f5f5f5; line-height: 1.5; }
  .container { max-width: 1100px; margin: 0 auto; padding: 20px; }
  .header { background: linear-gradient(135deg, #ef4444 0%, #b91c1c 100%); color: #fff; padding: 28px; text-align: center; border-radius: 10px; }
  .header h1 { margin: 0; font-size: 26px; font-weight: 600; }
  .header p { margin: 8px 0 0 0; font-size: 15px; opacity: 0.95; }
  .stats-grid { display: table; width: 100%; margin: 18px 0; border-spacing: 10px; }
  .stat-card { display: table-cell; background: #fff; padding: 18px; border-radius: 8px; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,0.08); }
  .stat-card.danger  { border-top: 4px solid #ef4444; }
  .stat-card.warning { border-top: 4px solid #f59e0b; }
  .stat-card.primary { border-top: 4px solid #0ea5e9; }
  .stat-card.muted   { border-top: 4px solid #64748b; }
  .stat-number { font-size: 28px; font-weight: 700; margin: 8px 0 0 0; }
  .stat-label  { color: #666; font-size: 12px; text-transform: uppercase; letter-spacing: .5px; }
  .ai-summary { background: #fffbeb; border: 1px solid #fcd34d; border-left: 4px solid #f59e0b; padding: 16px 20px; border-radius: 8px; margin: 18px 0; }
  .ai-badge { display: inline-block; background: #f59e0b; color: #fff; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 600; text-transform: uppercase; margin-bottom: 10px; }
  .ai-body { color: #333; font-size: 14px; white-space: pre-wrap; }
  .section { background: #fff; margin: 18px 0; padding: 22px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.08); }
  .section h2 { margin: 0 0 14px 0; font-size: 18px; border-bottom: 2px solid #ef4444; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  thead { background: linear-gradient(135deg, #ef4444 0%, #b91c1c 100%); }
  th { color: #fff; padding: 10px 8px; text-align: left; font-weight: 600; font-size: 12px; }
  td { padding: 10px 8px; border-bottom: 1px solid #eee; vertical-align: top; }
  tbody tr:nth-child(even) { background-color: #fafafa; }
  td.num { font-family: 'Courier New', monospace; white-space: nowrap; }
  .muted { color: #888; font-size: 11px; }
  .no-data { text-align: center; padding: 20px; color: #666; font-style: italic; }
  .no-data-success { background: #d4edda; border: 1px solid #c3e6cb; border-radius: 8px; padding: 24px; text-align: center; color: #155724; }
  .alert-card { background: #fff; border: 1px solid #fecaca; border-left: 4px solid #ef4444; border-radius: 8px; padding: 16px; margin-bottom: 12px; }
  .alert-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; gap: 12px; flex-wrap: wrap; }
  .alert-agent { color: #111; font-size: 15px; margin-right: 10px; }
  .alert-score { font-size: 22px; font-weight: 700; color: #b91c1c; background: #fee2e2; padding: 6px 14px; border-radius: 20px; }
  .alert-meta { color: #666; font-size: 12px; margin-bottom: 8px; display: flex; gap: 12px; flex-wrap: wrap; }
  .chip { display: inline-block; background: #eff6ff; color: #1e40af; padding: 3px 10px; border-radius: 12px; font-size: 11px; margin-left: 6px; }
  .improv-box { background: #f9fafb; border-left: 3px solid #9ca3af; padding: 8px 12px; margin-top: 8px; font-size: 13px; border-radius: 4px; }
  .improv-box.ai-box { border-left-color: #0ea5e9; background: #eff6ff; }
  .footer { text-align: center; padding: 18px; color: #777; font-size: 12px; margin-top: 20px; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Alertas Críticas de Calidad</h1>
    <p>{$date} · Umbral: {$threshold}%</p>
  </div>

  {$connError}

  <div class="stats-grid">
    <div class="stat-card danger">
      <div class="stat-label">Alertas críticas</div>
      <div class="stat-number">{$totals['total_alerts']}</div>
    </div>
    <div class="stat-card warning">
      <div class="stat-label">Agentes afectados</div>
      <div class="stat-number">{$totals['agents_affected']}</div>
    </div>
    <div class="stat-card primary">
      <div class="stat-label">Campañas afectadas</div>
      <div class="stat-number">{$totals['campaigns_affected']}</div>
    </div>
    <div class="stat-card muted">
      <div class="stat-label">Score promedio</div>
      <div class="stat-number">{$totals['avg_score']}%</div>
    </div>
    <div class="stat-card danger">
      <div class="stat-label">Score más bajo</div>
      <div class="stat-number">{$lowest}</div>
    </div>
  </div>

  {$aiBlock}

  <div class="section">
    <h2>Resumen por agente</h2>
    <table>
      <thead>
        <tr>
          <th>Agente</th>
          <th># Alertas</th>
          <th>Score mínimo</th>
          <th>Score promedio</th>
          <th>Campañas</th>
        </tr>
      </thead>
      <tbody>{$agentRows}</tbody>
    </table>
  </div>

HTML
            . (!empty($byCampaign)
                ? "<div class='section'><h2>Resumen por campaña</h2><table><thead><tr><th>Campaña</th><th># Alertas</th><th>Agentes</th></tr></thead><tbody>{$campaignRows}</tbody></table></div>"
                : "")
            . "<div class='section'><h2>Detalle de alertas</h2>{$detailBlocks}</div>"
            . "<div class='footer'><p><strong>Reporte generado automáticamente</strong></p>"
            . "<p>{$reportData['generated_at']} — Sistema de Control de Asistencia · Datos de hhempeos_calidad</p></div>"
            . "</div></body></html>";
    }
}

if (!function_exists('sendQualityAlertsReportByEmail')) {
    function sendQualityAlertsReportByEmail(PDO $pdo, array $reportData, array $recipients, string $aiSummary = ''): bool
    {
        if (empty($recipients)) {
            error_log('[quality_alerts_report] No recipients configured');
            return false;
        }

        $html = generateQualityAlertsReportHTML($reportData, $aiSummary);
        require_once __DIR__ . '/email_functions.php';

        $result = sendDailyQualityAlertsReport($html, $recipients, $reportData);

        if ($result['success']) {
            error_log('[quality_alerts_report] Sent: ' . $result['message']);
            return true;
        }
        error_log('[quality_alerts_report] Failed: ' . $result['message']);
        return false;
    }
}
